package models;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;


/**
* FoncierApp/ConnectionBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Foncier.idl
* samedi 14 octobre 2023 18 h 16 EAT
*/

public class ConnectionBase 
{

  public ConnectionBase ()
  {
  } // ctor

  private Connection connex;
  
    public Connection giveConSql() throws ClassNotFoundException, SQLException {
        String url = "jdbc:postgresql://localhost:5432/meuble";
        String utilisateur = "postgres";
        String motDePasse = "dbapg";
            Class.forName("org.postgresql.Driver");
            this.setConnex(DriverManager.getConnection(url, utilisateur, motDePasse));
        return this.connex;
    }

    private void setConnex(Connection connection) {
        this.connex=connection;
    }

} // class ConnectionBase
